#!/usr/bin/env bash
# Setup haproxy on server lb-01 to serve web-01 and web-02.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server 6401-web-01 184.72.196.72 check
        server 6401-web-02 3.88.21.88 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
